### ISSUE TITLE
Корректностб состояния 

### ISSUE THREAD

**Issue by difiozy** [KPAKEH-SP/ATM#5]
https://github.com/KPAKEH-SP/ATM/blob/d6ee52c8df56d03905a9e0f62bf7e09bb0df57d6/src/BanknoteStorage.java#L8C30-L8C30

Если я правильно понял логику программы то в случае, когда ты выводишь информацию о том что денег в банкомате недостаточно количество купюр все равно уменьшается, что кажется неверным, если я не прав то поправь меня

**Comment by KPAKEH-SP** [comment]
Когда купюры в банкомате всё ещё есть, но он не может выдать полностью сумму указанную пользователем, то он выдаёт те деньги, которые может, а потом выводит сообщение, что не может выдать оставшуюся сумму из-за нехватки средств. То-есть условно в банкомате лежит только 1 купюра номиналом 1000 (Все остальные номиналы отсутствуют), а пользователь хочет снять 2000. Ему выдадут 1 купюру номиналом 1000 и скажут, что оставшуюся 1000 банкомат выдать не может.
